Update patch set 1
Patch Set 1: Verified+1 Code-Review+2

Serves only for AOSP audio HAL since last year:
hardware/qcom/audio/hal/acdb.h:21:10: fatal error: 'linux/msm_audio_calibration.h' file not found

Patch-set: 1
Reviewer: Adrian DC <13589@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=+1
Label: Code-Review=+2